---
- name: install tzdata
  become: yes
  package:
    name: tzdata
    state: present

- name: configure timezone
  become: yes
  copy:
    content: "{{ timezone }}\n"
    dest: '/etc/timezone'
    owner: root
    group: root
    mode: 'u=rw,go=r'
  notify: timezone changed
